[package]
name = "inventori"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ini kalo pake sqllite
#rusqlite = "0.31.0"
#chrono = "0.4"
#tabled = "0.15" # Untuk membuat tampilan tabel di terminal

# ini pake postgre
tokio = { version = "1", features = ["full"] } # Untuk async
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "chrono"] }
chrono = "0.4"
tabled = "0.15"
